### ISSUE TITLE
ArcMap Line of Sight

### ISSUE THREAD

**Issue by apiszcz** [JanCaha/Line-of-Sight-Analyst#1]
Is this implementation the same as the Line of Sight capability including with ArcMap?
Thank you.

**Comment by JanCaha** [comment]
It should be fairly comparable. The general inspiration is from the Line of Sight tool and the results were tested against it. Unfortunately, there is no detailed description of the algorithm in Line of Sight so I can only guess and provide reasonable approximation of the algorithm.

But the result, visible/invisible, should be the same. Feel free to test it and report if you find any differences.

**Comment by apiszcz** [comment]
Thank you, your paper is great work, assume the tool is similar.
It appears we have to build the .tbx file correct?

**Comment by JanCaha** [comment]
You can just grab a release https://github.com/JanCaha/Line-of-Sight-Analyst/releases, extract the zip file (into folder that you have available in Catalog) and from the Catalog in ArcMap you should the toolbox correctly with all the tools. 

I am not sure if it is possible to build simple .tbx from python toolboxes.
